# Model Configuration
EMBED_DIM: 32
HIDDEN_DIM: 64
NUM_EXPERTS: 4
TOP_K: 2
NUM_CLASSES: 4
VOCAB_SIZE: 30522  # DistilBERT vocab size

# Training Configuration  
NUM_EPOCHS: 1
LEARNING_RATE: 0.001
BATCH_SIZE: 32
DEVICE: "cpu"  # Use CPU for local development (macOS compatible)

# Data Configuration
DATASET: "ag_news"
MAX_LENGTH: 256

# Paths
MODEL_PATH: "./results/toy_model/models/final_model.pt"
TOKENIZER_NAME: "distilbert-base-uncased"

# Class names for AG News
CLASS_NAMES: ['World', 'Sports', 'Business', 'Sci/Tech']

# Analysis Configuration
SAVE_PLOTS: true
OUTPUT_DIR: "./results/toy_model/analysis"
